### ISSUE TITLE
Bad display of cyrillic characters

### ISSUE THREAD

**Issue by jpcima** [jpcima/adljack#16]
@Wohlstand has reported the files with cyrillic characters as displaying incorrectly.
The locale used was `ru_RU.UTF-8`. I couldn't reproduce it.

![Снимок экрана от 2019-09-30 11-16-42](https://user-images.githubusercontent.com/17614485/65863437-67deae80-e370-11e9-9383-7199626096f9.png)

**Comment by Wohlstand** [comment]
Any non-ASCII, the same fails with Japanese:
![Снимок экрана от 2019-09-30 12-06-06](https://user-images.githubusercontent.com/6751442/65864545-b8f3a000-e37a-11e9-9bc6-95cb3ad1e205.png)

**Comment by jpcima** [comment]
Please check if it does same with a `PREFER_PDCURSES=ON` build, to verify if problem is terminal related.

**Comment by Wohlstand** [comment]
With PDCurses is same:
![Снимок экрана от 2019-09-30 12-15-00](https://user-images.githubusercontent.com/6751442/65865579-4388cf00-e37c-11e9-9e10-3d238fff1416.png)
The fact, this happens at my job PC but doesn't happen at my home, however, It was at my home also until some moment...

**Comment by jpcima** [comment]
It's normal that pdcurses doesn't show cyrillic, as it doesn't have the bitmap font for it.
What's shown is expected currentbehavior.

But still, it does indicate a thing: it does not translate into these "M-" bizarre char sequences.
Is MATE-terminal the terminal emulator used?

**Comment by Wohlstand** [comment]
It's not MATE, it's XFCE4's terminal
![Снимок экрана от 2019-09-30 12-32-15](https://user-images.githubusercontent.com/6751442/65866967-58fef880-e37e-11e9-82f6-a4ef0ed0a278.png)

**Comment by Wohlstand** [comment]
The same happens with Gnome terminal also. Is that because of ncurses-side setup? Or ncrurses/ncursesw?

**Comment by jpcima** [comment]
Seems I didn't have more luck reproducing this on XFCE one.
Ncurses is supposed to be the ncursesw one.

**Comment by jpcima** [comment]
Hi, I confirm non-wide ncurses as **not** displaying correct characters.
Make sure that it's ncursesw the library linked into adlrt.
In CMake, ordinary ncurses is picked as fallback, probably I shouldn't do that.

**Comment by Wohlstand** [comment]
So, I had that crap even `libncursesw5-dev` was installed, however, yeah, I have nuked entire "build" folder and I have ran build from scratch, so, the problem has gone, finally! :fox_face: 
![Снимок экрана от 2019-10-03 14-07-00](https://user-images.githubusercontent.com/6751442/66121996-40dde200-e5e7-11e9-94ab-e4774bd3210d.png)

**Comment by jpcima** [comment]
Great. :+1:  :fox_face:
In the last commit, I forced linking the wide ncurses versions.
