### ISSUE TITLE
dependency for ALSA unclear

### ISSUE THREAD

**Issue by Newk77** [jpcima/adljack#18]
hi! wonderfull instrument you made here! (played with it in Manjaro)
I am trying to install this on a Raspberry Pi ZeroW, but these pop up during the config process of cmake:
```
!!   virtualMIDI: NO
!!   RtAudio system library: NO
!!   RtMidi system library: NO
```

which i think results in adlrt after compiling, installing and starting to output:
```
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApiPulse::probeDeviceOpen: error connecting output to PulseAudio server.
Aborted
```
what should be in place for this to work? This only works with PulseAudio running?

**Comment by jpcima** [comment]
Hi,! I'll have to make a proper fix when Pulseaudio, but for now, try like this:

Delete the following block of `RtAudio.cmake`.
This is expected to removes pulseaudio support entirely, and proceed direct to ALSA.

https://github.com/jpcima/adljack/blob/8a1da749826479d38f03467fe84ef6e0fecf0dce/cmake/RtAudio.cmake#L7-L12

**Comment by jpcima** [comment]
And, I almost forgot the more obvious way.

You can type: `adlrt -A alsa` which forces it to select ALSA as sound system instead of Pulse.

Typing `adlrt --help` shows you the full information.

**Comment by Wohlstand** [comment]
Good note, I'll try to do that as soon as possible.

**Comment by Wohlstand** [comment]
I added a small paragraph into "ReadMe", into "Questions" paragrap.
