### ISSUE TITLE
No Midi Input devices on Windows 7

### ISSUE THREAD

**Issue by Bassian** [jpcima/adljack#22]
my problem is ADLjack can't find any MiDi input devices and thus won't work
do i need the OPNMidi and/or OPLMidi first?

for clarification, i want to use the OPNMidi with dosbox

**Comment by Bassian** [comment]
and before you say "Use Windows 10" i can't due to bootcamp issues

**Comment by Wohlstand** [comment]
You need to use some sort of a LoopMidi to connect MIDI software between each other

**Comment by Wohlstand** [comment]
BTW, isn't the thing can work on macOS natively? Or you do need this on your Windows VM especially?

**Comment by jpcima** [comment]
Hello, it can be used as MIDI driver, like @Wohlstand told earlier, this needs to install LoopMidi.
This installs a necessary driver, then the system is able to work.

But there's a potential license issue with using this system, it's why I don't advertise it a lot.
I was not able to contact the driver author the last time when I tried.

I have already managed to make it work together with DOSBox.

**Comment by Bassian** [comment]
nvm i was just stupid and found the OPN Midi driver
