### ISSUE TITLE
No source tarball for 1.3.0

### ISSUE THREAD

**Issue by dvzrv** [jpcima/adljack#25]
Hi! While trying to upgrade to 1.3.0 I ran into the issue, that no source tarball for the release is available.
The auto-generated tarballs do not contain git submodules. Can you please add one?

**Comment by Wohlstand** [comment]
Oh, let me to archive and upload the full tarball... At projects that I do maintain by myself, I always attach separated source code tarballs that includes submodules too (the `git archive-all` plugin).

**Comment by Wohlstand** [comment]
Done, I attached full source code archives just now. Have fun!
