### ISSUE TITLE
git build fails

### ISSUE THREAD

**Issue by grammoboy2** [jpcima/adljack#27]
```
build]$ cmake -DCMAKE_BUILD_TYPE=Release ..

CMake Error at CMakeLists.txt:35 (add_subdirectory):
  The source directory

    /home/user/git/adljack/thirdparty/libADLMIDI

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:36 (add_subdirectory):
  The source directory

    /home/user/git/adljack/thirdparty/libOPNMIDI

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:37 (add_subdirectory):
  The source directory

    /home/user/git/adljack/thirdparty/flatbuffers

  does not contain a CMakeLists.txt file.

```

**Comment by Wohlstand** [comment]
This repository uses submodules: you forgot to download them, please perform:
```
git submodule init
git submodule update
```
and retry to configure the build.

**Comment by grammoboy2** [comment]
I see, missed it from the README, but that's what --recursive seems to be doing

**Comment by grammoboy2** [comment]
In file included from /home/archie/git/adljack/sources/state.cc:8:
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::State::Verify(flatbuffers::Verifier&) cons
’:
/home/archie/git/adljack/sources/state_generated.h:46:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::Vector<flatbuffers::Offset<fb::state::Channel_State> >*)’
   46 |            verifier.Verify(channel()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/buffer_ref.h:21,
                 from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:27,
                 from /home/archie/git/adljack/sources/state_generated.h:7:
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:46:27: note:   couldn’t deduce template parameter ‘T’
   46 |            verifier.Verify(channel()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier:
Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:49:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::Vector<flatbuffers::Offset<fb::state::Player_State> >*)’
   49 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:49:27: note:   couldn’t deduce template parameter ‘T’
   49 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier:
Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:51:32: error: no matching function for call to ‘fb::state::State::VerifyField<uint8_t>(flatbuffers::Verifier&, fb::state::State::<unnamed enum>) const’
   51 |            VerifyField<uint8_t>(verifier, VT_CHIP_COUNT) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffer_builder.h:36,
                 from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:29:
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h:52:33: error: no matching function for call to ‘fb::state::State::VerifyField<uint16_t>(flatbuffers::Verifier&, fb::state::State::<unnamed enum>) const’
   52 |            VerifyField<uint16_t>(verifier, VT_VOLUME) &&
      |            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Channel_State::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:137:32: error: no matching function for call to ‘fb::state::Channel_State::VerifyField<uint8_t>(flatbuffers::Verifier&, fb::state::Channel_State::<unnamed enum>) const’
  137 |            VerifyField<uint8_t>(verifier, VT_PROGRAM) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h:138:33: error: no matching function for call to ‘fb::state::Channel_State::VerifyField<uint16_t>(flatbuffers::Verifier&, fb::state::Channel_State::<unnamed enum>) const’
  138 |            VerifyField<uint16_t>(verifier, VT_BANK) &&
      |            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Player_Id::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:188:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  188 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:188:27: note:   couldn’t deduce template parameter ‘T’
  188 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier:
Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:190:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  190 |            verifier.Verify(emulator()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:190:27: note:   couldn’t deduce template parameter ‘T’
  190 |            verifier.Verify(emulator()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier:
Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Player_State::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:254:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  254 |            verifier.Verify(bank_file()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:254:27: note:   couldn’t deduce template parameter ‘T’
  254 |            verifier.Verify(bank_file()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier:
Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [CMakeFiles/adljack.dir/build.make:216: CMakeFiles/adljack.dir/sources/state.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/adljack.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by Wohlstand** [comment]
Now the question: what OS you do run? What version of your compiler?

**Comment by grammoboy2** [comment]
arch linux 
gcc version 13.2.1 20230801 (GCC)

**Comment by grammoboy2** [comment]
I haven't installed flatbuffers, is it needed? 

```looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing rtaudio (6.0.1-1) breaks dependency 'librtaudio.so=6-64' required by clap-example-host```

**Comment by Wohlstand** [comment]
No, there is pre-included flatbuffers tha gets built in a place. I made a small tweak, please run `git pull` and try to rebuild.

**Comment by grammoboy2** [comment]
rm -rf build
git pull
mkdir build etc

```[ 77%] Building CXX object CMakeFiles/adljack.dir/sources/state.cc.o
In file included from /home/archie/git/adljack/sources/state.cc:8:
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::State::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:46:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::Vector<flatbuffers::Offset<fb::state::Channel_State> >*)’
   46 |            verifier.Verify(channel()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/buffer_ref.h:21,
                 from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:27,
                 from /home/archie/git/adljack/sources/state_generated.h:7:
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:46:27: note:   couldn’t deduce template parameter ‘T’
   46 |            verifier.Verify(channel()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier::Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:49:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::Vector<flatbuffers::Offset<fb::state::Player_State> >*)’
   49 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:49:27: note:   couldn’t deduce template parameter ‘T’
   49 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier::Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:51:32: error: no matching function for call to ‘fb::state::State::VerifyField<uint8_t>(flatbuffers::Verifier&, fb::state::State::<unnamed enum>) const’
   51 |            VerifyField<uint8_t>(verifier, VT_CHIP_COUNT) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffer_builder.h:36,
                 from /home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:29:
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h:52:33: error: no matching function for call to ‘fb::state::State::VerifyField<uint16_t>(flatbuffers::Verifier&, fb::state::State::<unnamed enum>) const’
   52 |            VerifyField<uint16_t>(verifier, VT_VOLUME) &&
      |            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Channel_State::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:137:32: error: no matching function for call to ‘fb::state::Channel_State::VerifyField<uint8_t>(flatbuffers::Verifier&, fb::state::Channel_State::<unnamed enum>) const’
  137 |            VerifyField<uint8_t>(verifier, VT_PROGRAM) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h:138:33: error: no matching function for call to ‘fb::state::Channel_State::VerifyField<uint16_t>(flatbuffers::Verifier&, fb::state::Channel_State::<unnamed enum>) const’
  138 |            VerifyField<uint16_t>(verifier, VT_BANK) &&
      |            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note: candidate: ‘template<class T> bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const’
  125 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/table.h:125:8: note:   candidate expects 3 arguments, 2 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Player_Id::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:188:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  188 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:188:27: note:   couldn’t deduce template parameter ‘T’
  188 |            verifier.Verify(player()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier::Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h:190:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  190 |            verifier.Verify(emulator()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:190:27: note:   couldn’t deduce template parameter ‘T’
  190 |            verifier.Verify(emulator()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier::Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
/home/archie/git/adljack/sources/state_generated.h: In member function ‘bool fb::state::Player_State::Verify(flatbuffers::Verifier&) const’:
/home/archie/git/adljack/sources/state_generated.h:254:27: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  254 |            verifier.Verify(bank_file()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note: candidate: ‘template<class T> bool flatbuffers::Verifier::Verify(size_t) const’
   92 |   template<typename T> bool Verify(const size_t elem) const {
      |                             ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:92:29: note:   template argument deduction/substitution failed:
/home/archie/git/adljack/sources/state_generated.h:254:27: note:   couldn’t deduce template parameter ‘T’
  254 |            verifier.Verify(bank_file()) &&
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note: candidate: ‘bool flatbuffers::Verifier::Verify(size_t, size_t) const’
   76 |   bool Verify(const size_t elem, const size_t elem_len) const {
      |        ^~~~~~
/home/archie/git/adljack/thirdparty/flatbuffers/include/flatbuffers/verifier.h:76:8: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [CMakeFiles/adljack.dir/build.make:216: CMakeFiles/adljack.dir/sources/state.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/adljack.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by grammoboy2** [comment]
Any chance that you could fix this in the coming weeks?

Or can I disable flatbuffers for building, just to look in to this issue?
https://github.com/jpcima/adljack/issues/28

**Comment by Wohlstand** [comment]
I'll take a deeper look soon.

**Comment by Wohlstand** [comment]
Now there are questions:
- What the distro you do use?
- What compiler versions you do use? (hint: they gets reported by CMake on first run, you may wipe your "build" and run cmake from the scratch again)

I asking, just, because I need to know what the place where you do build. On my end (gcc-9, gcc-13, and clang) do build the thing fine, even Flatbuffers.

**Comment by grammoboy2** [comment]
Arch Linux

```
$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_NO_PIE
-- Performing Test HAS_NO_PIE - Success
==== libADLMIDI options ====
libADLMIDI_STATIC        = ON
libADLMIDI_SHARED        = OFF
WITH_UNIT_TESTS          = OFF
WITH_MIDI_SEQUENCER      = OFF
WITH_EMBEDDED_BANKS      = ON
WITH_HQ_RESAMPLER        = OFF
WITH_MUS_SUPPORT         = OFF
WITH_XMI_SUPPORT         = OFF
USE_DOSBOX_EMULATOR      = ON
USE_NUKED_EMULATOR       = ON
USE_OPAL_EMULATOR        = ON
USE_JAVA_EMULATOR        = ON
===== Utils and extras =====
WITH_GENADLDATA          = OFF
WITH_GENADLDATA_COMMENTS = OFF
WITH_MIDIPLAY            = OFF
MIDIPLAY_WAVE_ONLY       = OFF
WITH_ADLMIDI2            = OFF
WITH_VLC_PLUGIN          = OFF
WITH_OLD_UTILS           = OFF
WITH_MUS2MID             = OFF
WITH_XMI2MID             = OFF
EXAMPLE_SDL2_AUDIO       = OFF
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
== Your C++ compiler supports C++14, YMFM emulator will be ENABLED
==== libOPNMIDI options ====
libOPNMIDI_STATIC        = ON
libOPNMIDI_SHARED        = OFF
WITH_UNIT_TESTS          = OFF
WITH_MIDI_SEQUENCER      = OFF
WITH_HQ_RESAMPLER        = OFF
WITH_MUS_SUPPORT         = OFF
WITH_XMI_SUPPORT         = OFF
USE_MAME_EMULATOR        = ON
USE_GENS_EMULATOR        = ON
USE_NUKED_EMULATOR       = ON
USE_NP2_EMULATOR         = ON
USE_MAME_2608_EMULATOR   = ON
USE_VGM_FILE_DUMPER      = ON
USE_YMFM_EMULATOR        = ON
===== Utils and extras =====
WITH_MIDIPLAY            = OFF
WITH_WOPN2HPP            = OFF
WITH_VLC_PLUGIN          = OFF
WITH_DAC_UTIL            = OFF
WITH_EXTRA_BANKS         = OFF
-- Proceeding with version: 23.5.26.14
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Looking for strtoull_l
-- Looking for strtoull_l - found
-- Looking for realpath
-- Looking for realpath - found
-- CMAKE_CXX_FLAGS:  -Wall
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Intl: built in to C library
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: /usr/lib/libc.so
-- Found Gettext: /usr/bin/msgmerge (found version "0.22.4")
-- Curses include dir: /usr/include
-- Curses library: /usr/lib/libncursesw.so
-- Checking for module 'jack'
--   Found jack, version 1.9.22
-- Checking for module 'libpulse-simple'
--   Found libpulse-simple, version 17.0
-- Checking for module 'liblo'
--   Found liblo, version 0.31
-- Looking for mlockall
-- Looking for mlockall - found
!! Feature summary:
!!   Curses: YES
!!   PdCurses: NO
!!   Jack: YES
!!   LibLO: YES
!!   Pulseaudio: YES
!!   virtualMIDI: NO
!!   RtAudio system library: NO
!!   RtMidi system library: NO
!!   gettext: YES
!!   POSIX mlockall: YES

**Comment by Wohlstand** [comment]
Good news, with a help of my friend @SkullGamer205 who also runs Arch Linux, I found a solution for this bug.

Please run:
```bash
git pull
```
and then try to build the thing again. Let me know if it builds or not. I will make a new release tag with this fix.

**Comment by grammoboy2** [comment]
Builds. Thanks.
