### ISSUE TITLE
CMake Error at CMakeLists.txt:43

### ISSUE THREAD

**Issue by barotto** [jpcima/adljack#6]
Hello, I'm getting this cmake error:
```
CMake Error at CMakeLists.txt:43 (add_library):
  Target "pdcurses" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
  has leading or trailing whitespace.  This is now an error according to
  policy CMP0004.
```
Though the configuration completes successfully and the code compiles without errors.

My OS is Ubuntu 16.04 (cmake version 3.5.1)

**Comment by jpcima** [comment]
Hello. I have met this error before, and also currently as I try to set up automated builds.
This will be benign as far as I am aware.
Anyway I just pushed to master a fix which I had in the works. Please check now.

**Comment by barotto** [comment]
Tested the current master, I'm not getting the error anymore.
Closing.
