### ISSUE TITLE
nouvelle version ?

### ISSUE THREAD

**Issue by trebmuh** [jpcima/adljack#7]
Je vois qu'il y a 48 commits depuis la version 1.0.0 .
Penses-tu relâcher une nouvelle version d'ici peu ?

**Comment by jpcima** [comment]
Il faut tâcher de faire ça si possible. J'ai une pile d'améliorations absolument majeures à intégrer, qui sont à vrai dire surtout du côté des librairies sous-jacentes et non de adljack lui-même.

À peine hier soir, j'ai contribué une fonctionnalité très désirable à ADLMIDI pour améliorer la gestion de la polyphonie. Ca demande une phase de test, et puis de rétro-porter (ça se dit?) les modifs entre ADLMIDI et OPNMIDI pour les tenir à niveau.

C'est surtout cette mise à niveau à faire qui me retient de sortir une version nouvelle. Cela dit, je ne pense pas que cela représente un grand travail.
À partir de la, on peut songer à emballer ça en 1.1.0-rc.

Dans le journal des changements il y aura : (d'après ce que j'ai en tête, mais il y a tellement de choses)
- [X] synthèse à taux d'échantillonage natif améliorant fortement le niveau de fidélité des émulateurs DosBox, Gens, MAME
- [X] mise à niveau de l'émulateur DosBox
- [X] réechantillonage haute qualité Zita-resampler
- [X] support du MIDI amélioré : correction de Pitchbend et de l'Aftertouch
- [X] correction de l'agencement automatique des canaux 4op
- [X] correction des notes à long sustain coupant prématurément

**Comment by jpcima** [comment]
Les mises à niveaux, les banques, les tests : tout a l'air bon. J'ai sorti la rc1.
https://github.com/jpcima/adljack/releases/tag/v1.1.0-rc.1

**Comment by trebmuh** [comment]
Je viens de tenter une compilation à partir du tarball "complete sources". Malheureusement, je n'obtiens pas la compilation des .po en .mo . L'étape de configuration me dit ceci :
```
CMake Warning at CMakeLists.txt:41 (find_package):
  By not providing "FindIconv.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Iconv", but
  CMake did not find one.

  Could not find a package configuration file provided by "Iconv" with any of
  the following names:

    IconvConfig.cmake
    iconv-config.cmake

  Add the installation prefix of "Iconv" to CMAKE_PREFIX_PATH or set
  "Iconv_DIR" to a directory containing one of the above files.  If "Iconv"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Curses include dir: /usr/include
-- Curses library: /usr/lib/x86_64-linux-gnu/libncurses.so
!! Feature summary:
!!   Curses: YES
!!   PdCurses: NO
!!   Jack: YES
!!   LibLO: YES
!!   Pulseaudio: YES
!!   virtualMIDI: NO
!!   gettext: NO
!!   POSIX mlockall: YES
-- Configuring done
```
Le `gettext: NO` semble être le coupable. J'ai pourtant bien les paquets gettext et libc-bin (qui contient iconv) installés sur le système.

Une idée ?

**Comment by jpcima** [comment]
> Une idée ?

Ouaip je sais pourquoi. FindIconv provient de cmake, mais il n'y existe qu'a partir d'une version donnée que n'a pas debian stretch.

Je pourrai surement te fournir un patch qui intègre FindIconv à adljack.
En vérité, on peut surement enlever `find_package(Iconv)` en ce qui concerne Linux, car à ma connaissance iconv est inclue dans la runtime C et ne nécessite rien de spécial. C'est principalement pour gérer Windows.

**Comment by jpcima** [comment]
@trebmuh  Voici un patch qui intègre `FindIconv`.
https://github.com/jpcima/adljack/commit/5ab9385b47a1e69e5935c80ae646831594e13459.diff

**Comment by trebmuh** [comment]
Nickel. Tout fonctionne à présent. Merci pour la rustine :+1:

**Comment by trebmuh** [comment]
@jpcima tu as une idée de la date de sortie de la 1.1.0 (pas -rc) ?

**Comment by jpcima** [comment]
La 1.1.0-rc1 sera identique à la release, rien à ajouter.
Il y aurait uniquement à réemballer la rc en changeant le numéro de version.

Peu après la 1.1.0 il y a eu des ajouts de fonctionnalités qui auraient leur place davantage dans une version à part entière. Vu que la dernière master est sans problème, je pourrai alors sortir sans doute ces deux versions : 1.1.0 et 1.2.0.

J'ai focalisé mon travail sur la VST d'OPL3 surtout qui est dans un état désormais utilisable https://github.com/jpcima/adlplug
(un "concurrent" de la JuceOPLVST bien plus avancé en fonctionnalités)

Par ailleurs je travaille maintenant à finaliser un nouveau programme que j'annoncerai bientôt si tout va bien. :ok_hand: (surprise, ou pas nécessairement si tu as vu mon activité récente)

**Comment by trebmuh** [comment]
ack :)

**Comment by jpcima** [comment]
Sortie de la 1.1.0

https://github.com/jpcima/adljack/releases/tag/v1.1.0

**Comment by trebmuh** [comment]
@jpcima : c'est étrange, https://github.com/jpcima/adljack/releases/tag/v1.1.0 semble dire qu'il y a eu 18 commits depuis cette version, ce qui ferait en sorte que le fanion -a ne soit pas de la partie.

**Comment by jpcima** [comment]
@trebmuh Le fanion `-a` est bien inclus dans cette version. Sur quoi bases-tu cette affirmation ?

J'ai simplement réalisé une branche release-1.1.0 basée sur le tag RC, sur laquelle j'ai uniquement ajouté le commit qui implémente `-a` et rien d'autre.

**Comment by trebmuh** [comment]
> Sur quoi bases-tu cette affirmation ?

Sur ce qui est écrit ici : https://github.com/jpcima/adljack/releases/tag/v1.1.0

![adljack](https://user-images.githubusercontent.com/8705846/44117679-4634481c-a014-11e8-931c-bd869037cf73.png)

**Comment by jpcima** [comment]
Cette release n'est pas à l'image de la master actuelle.
C'est un fork de la RC + juste le patch `-a`.

Tu peux consulter ici l'historique de cette version.
https://github.com/jpcima/adljack/commits/v1.1.0

Les 18 commits se situent dans la période 16 juin-13 août, que je n'ai délibérément pas inclus dans cette version. C'est pour celle d'après.
La prochaine ajoutera le support du CC soft panning et pas grand chose de plus de bien important.

**Comment by trebmuh** [comment]
OK.

Je ferme ici maintenant qu'une nouvelle version est là, et une autre est en route.
