### ISSUE TITLE
auto-connection à jackd

### ISSUE THREAD

**Issue by trebmuh** [jpcima/adljack#8]
Ça serait super si les sorties audio pouvaient s'auto-connecter aux sorties "system" du graph de jackd. Un switch en CLI serait idéal car on pourrait alors choisir d'utiliser cette fonctionnalité (ou pas, cas d'un gestionnaire de session par exemple).

**Comment by jpcima** [comment]
Je vois pas trop l'intérêt de ce truc lorsqu'il existe la baie de brassage de Qjackctl et autres.
Enfin pourquoi pas.

**Comment by trebmuh** [comment]
L'intérêt principal est le côté facile-à-utiliser pour un débutant. Tu lances le biniou, ça s'auto-connecte _de base_, et le son sort directement.

Pour les utilisateurs plus avancés, on supprime l'auto-connexion avec le switch en CLI.

**Comment by jpcima** [comment]
Je trouve ce comportement indésirable lorsqu'il est activé par défaut.

Pour peu d'avoir une gestion de connexions en externe, alors on se retrouve avec une connexion au port système indésirable qu'on est obligé de dégager manuellement.

Personnellement, je démarre le programme par la lanceur de menu 9 fois sur 10, je ne souhaite pas passer par la console chaque fois, pour faire que le programme se comporte comme je veux.

**Comment by trebmuh** [comment]
Dans les gestionnaires de connexion/session (ie: gladish et cadence au moins), il y a une case permettant de refuser l'auto-connexion.

Le lanceur de menu, grâce à un swith en CLI qui y est ajoutable, permet également de désactiver l'auto-connexion.

**Comment by jpcima** [comment]
J'utilise un logiciel qui n'a pas cette fonctionnalité, et peut-être que des utilisateurs sont dans le même cas.

Je te propose un compromis : je rends la connection automatique possible à l'aide d'un fanion. Je conserve le comportement par défaut tel que c'est maintenant.

Tu peux éditer les fichiers desktop comme cela te plait. Est-ce que ça te semble raisonnable ?

**Comment by trebmuh** [comment]
Carrément, j'étais même en chemin pour mentionner la même chose ici !
:+1:

**Comment by jpcima** [comment]
J'ai mis un fanion -a. Tu veux bien faire un test de ton côté ?

**Comment by trebmuh** [comment]
Testé, et ça semble fonctionner nickel. Merci @jpcima !

**Comment by jpcima** [comment]
Ok chouette. Je tacherai d'inclure ça dans la release.

Hs : tu veux bien m'aider à corriger une fois encore la syntaxe wiki ? j'arrive pas à trouver la fameuse option html. http://linuxmao.org/JPC+Ensemble+Chorus
